# Generated by Django 3.1 on 2020-08-31 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sohamindustryapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='companyform1',
            new_name='companyform2',
        ),
    ]
